### ISSUE TITLE
Flutter 3.27 Issue

### ISSUE THREAD

**Issue by ihadabs** [yako-dev/flutter-status-alert#17]
Xcode build done.                                           148.0s
Failed to build iOS app
Error (Xcode): ../../../../../../../.pub-cache/hosted/pub.dev/flare_flutter-3.0.2/lib/provider/asset_flare.dart:25:23: Error: The method 'hashValues' isn't defined for the class 'AssetFlare'.

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.

**Comment by fmsidoe** [comment]
For now replace status_alert in your pubspec.yaml for now with:

```
  status_alert:
    git:
      url: https://github.com/fmsidoe/flutter-status-alert.git
      ref: master
```


Dont think this project will be updated anymore
